////
REMOVED in CS6 restructure.

Why: Schema-definition content (XML snippets for custom content types,
display-name-expression, list-title-expression, the allow-new-content config
flag) belongs in the XP CMS content-types documentation, not in Content
Studio's editor-facing docs. The new content-types.adoc page links out to
that reference instead of duplicating the XML.

What was kept in docs/content-types.adoc: A trimmed, editor-facing description
of the built-in content types (Folder, Shortcut, Site, Page template,
Templates folder, Image, Unstructured) focused on how they behave in the
Content Studio UI.

What was dropped (preserved here for review):
- The "Custom content types" section with the <content-type> XML sample
  and the <allow-new-content> config flag explanation.
- The "Display name expression" section.
- The "List title expression" section.
- The longer "Page components" and "Rendering other content" explanations
  that repeated the visual-editor docs.

If any of this is still worth saying for editors, consider adding a short
summary to content-types.adoc; do NOT inline the XML.
////

== Custom content types

Custom content type can be built by implementing a content type schema as described https://developer.enonic.com/docs/xp/stable/cms/content-types#form_definition[here].
In addition to the fields described on that page, content type schema supports optional `config` object with additional configuration of
content type behaviour in Content Studio.

[source,xml]
----
<content-type>
  <display-name>Person</display-name>
  <super-type>base:structured</super-type>
  <form>
    <input name="firstName" type="TextLine">
      <label>First Name</label>
    </input>
    <input name="lastName" type="TextLine">
      <label>Last Name</label>
    </input>
    <input name="city" type="TextLine">
      <label>City</label>
    </input>
  </form>
  <config> // <1>
    <allow-new-content>false</allow-new-content> // <2>
  </config>
</content-type>
----
<1> *config* Optional object that defines content type behaviour in the Content Studio.
<2> *allow-new-content* (default: `true`) When set to `false`, removes the content type from the "New Content" modal dialog.
Existing content items of this type will not be affected. New content of this type can still be created via
https://developer.enonic.com/docs/xp/stable/api/lib-content[Content API].

== Display name expression

It's possible to auto-generate display name based on values from the form fields by using ES6 template literals.
In the example below, the display name will consist of the values from the `firstName` and `lastName` fields, separated by a space.

NOTE: Only simple input types may be used as variables, so input types like HtmlArea or CheckBox are not supported. Additionally, if an input allows multiple occurrences, only the first occurrence will be used in the generated display name.

[source,xml]
----
<content-type>
  <display-name>Person</display-name>
  <display-name-expression>${firstName} ${lastName}</display-name-expression>
  <form>
    <input name="firstName" type="TextLine">
      <label>First Name</label>
    </input>
    <input name="lastName" type="TextLine">
      <label>Last Name</label>
    </input>
  </form>
</content-type>
----

== List title expression

This config is similar to display-name-expression but used for displaying a composite content
title in the Content Studio's Content Browser. For example, by defining an expression like in the example below you can combine three field values
with some static text.

[source,xml]
----
<content-type>
  <display-name>Person</display-name>
  <super-type>base:structured</super-type>
  <form>
    <input name="firstName" type="TextLine">
      <label>First Name</label>
    </input>
    <input name="lastName" type="TextLine">
      <label>Last Name</label>
    </input>
    <input name="city" type="TextLine">
      <label>City</label>
    </input>
  </form>
  <config>
    <list-title-expression>${data.firstName} ${data.lastName} from ${data.city}</list-title-expression>
  </config>
</content-type>
----
